{% set name = "naturalneighbor" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/naturalneighbor-{{ version }}.tar.gz
  sha256: 647b5922c3787887c04be7748f8112a1720b1323c8e86b4c6665ce7eee89aee7

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py>=312]
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - setuptools <65
  host:
    - python
    - numpy >=1.13,<1.24
    - pip
    - setuptools <65
  run:
    - python
    - numpy >=1.13,<1.24

test:
  files:
    - tests/
  imports:
    - naturalneighbor
  commands:
    - pip check
    - pytest tests
  requires:
    - pytest
    - scipy
    - pip

about:
  home: https://github.com/innolitics/natural-neighbor-interpolation
  summary: Fast, discrete natural neighbor interpolation in 3D on a CPU.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Dhananjhay
